HW2 is completed
leksss/hw-test pull request #2
Opened 2021-06-20 08:55 UTC by leksss

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-06-24 05:40 UTC, kulti requested changes
Алексей, решение получилось сложное, запутанное, с лишним абстракциями в виде функций и типа element. Строка обходится несколько раз, а потом еще один цикл, который собирает результат. Также есть непонимание, что такое строка, как она связана с рунами и байтами.

Предлагаю сделать задание без звездочки. Все уместить в один цикл внутри функции Unpack. Сейчас важно правильно поработать со строками. Да и в принципе в Go принято делать решения попроще :)

2021-06-24 05:40 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	charRunes := []rune(char)
Кажется, вы не разобрались, как устроены строки в Go.

Какую идею должен выражать этот код?

`chars[pos]` — вернет один байт. Это не символ (не руна). И нет никакого смысла преобразовывать этот байт строку, а затем в слайс рун. Никакой новой полезной информации это не даст. Соответственно все что далее работает некорректно.

2021-06-24 15:06 UTC, leksss commented on hw02_unpack_string/unpack.go
> +	charRunes := []rune(char)
Тесты проходят, в том числе и на кириллические строки.

2021-06-25 04:57 UTC, leksss commented on hw02_unpack_string/unpack.go
> +	charRunes := []rune(char)
Сделал код компактней

2021-06-29 15:49 UTC, kulti requested changes
Алексей, еще раз предлагаю сдать ДЗ без звездочки. У нас будут сессии разбора ДЗ, где можно будет посмотреть на подходы к решению в том числе и заданий со звездочкой.

Сейчас решение получается очень сложное и запутанное. Не уверен, что оно работает, т.к. не понял его до конца. В нем лишняя алгоритмическая сложность (лишние циклы). Лишние выделения памяти. Много состояний.

2021-06-29 15:49 UTC, kulti commented on hw02_unpack_string/go.mod
> +module hw02unpackstring
Должно быть `github.com/leksss/hw-test/hw02_unpack_string`. go get прошел, видимо, потому что гитхаб закэшировал предыдущий верный вариант 😂

2021-06-29 15:49 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		}
Цикл назад — это квадратичная сложность.

2021-06-29 15:49 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		isEscaped = !(slashCount%2 == 0)
Это очень сложно. Достаточно помнить, что предыдущий символ был неэкранированный слэш.

2021-06-29 15:49 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		if unicode.IsDigit(r) && unicode.IsDigit(pr) && !isEscaped && !isPrevEscaped {
Что-то это условие совсем непонятное. Если цифра и перед ней цифра — это уже невалидная строка. Где-то какое-то тайное знание есть.

2021-06-29 15:49 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	unpackedStrings := make([]string, utf8.RuneCountInString(inputString))
Это все лишние аллокации. Строку можно обойти сразу по рунам (range inputString). И результаты можно сразу в strings.Builder писать. Но текущее решение на это не ляжет, конечно.

2021-06-30 04:25 UTC, leksss commented on hw02_unpack_string/unpack.go
> +		if unicode.IsDigit(r) && unicode.IsDigit(pr) && !isEscaped && !isPrevEscaped {
Это условие для определения что подряд две цифры и обе не экранированы. 
Тест TestUnpackInvalidString
"aaa10b"

2021-07-07 15:50 UTC, kulti requested changes
Алексей, про это решение уже можно говорить и что-то пытаться в нем понять. Оно все равно сложное и некорректное.

Вы уже многое попробовали, поэтому подскажу вам направление, чтобы вы смогли запрограммировать простое и понятное решение.

Строку "a3bc0" можно рассматривать как три кусочка: a3, b и c0. Каждый из них распаковывается очевидным образом. То базовая идея будет такая:
1. Идем последовательно по строке `for _, r := range inputString`. Никакие индексы и дополнительные слайсы не нужны.
2. Видим a и запоминаем ее в переменной pr (которая вне цикла, чтобы этот стейт между циклами сохранять).
3. Видим цифру 3 — записываем pr (a) 3 раза и сбрасываем pr в 0.
4. Видим b запоминаем ее в pr.
5. Видим с, видим, что в pr что-то есть. Записываем pr (b) один раз, и в pr кладем c.
6. Видим 0 — записываем pr (с) 0 раз и сбрасываем pr в 0.

Я специально опустил некоторые моменты, чтобы было еще над чем подумать. Суть в том, что на каждом шаге мы смотрим только на текущую руну и делаем одно из действий в зависимости от наличия предыдущей руны.

2021-07-07 15:50 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		if pos > 0 {
А если в строке будет всего один символ?

2021-07-07 15:50 UTC, kulti commented on hw02_unpack_string/unpack.go
> +				sb.WriteRune(r)
Пытаясь понять этот набор ифчиков мозг просто взрывается. Почему тут не произойдет так, что не сработают все три или хотя бы два? Это главный вопрос к этому коду, над которым нужно очень хорошо думать. Хороший код — простой, из него сразу должно быть понятно, что именно произойдет.

2021-08-15 16:46 UTC, kulti approved these changes
Алексей, теперь решение корректное за исключением игнорирования ошибки.

Обязательно посмотрите разбор этого ДЗ (видео прикреплено к занятию с разборами ДЗ).

ДЗ принято 8/10

2021-08-15 16:46 UTC, kulti commented on hw02_unpack_string/unpack.go
> +				repeatCnt, _ = strconv.Atoi(string(cr))
Не стоит игнорировать ошибки. Даже если считаете, что это невозможно, то все равно стоит вернуть ошибку, на случай если что-то пойдет не так.

2021-08-15 16:46 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			}
Покажу, как этот же код написать компактнее и лаконичнее:
```
	if !unicode.IsDigit(cr) {
		sb.WriteRune(pr)
	} else {
		repeatCnt, err := strconv.Atoi(string(cr))
		if err != nil {
			return fmt.Errorf("convert repeat counter: %w", err)
		}
		sb.WriteString(strings.Repeat(string(pr), repeatCnt))
	}
```

2021-08-15 16:46 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	lastRune, _ := utf8.DecodeLastRuneInString(inputString)
А что будет в pr к моменту выхода из цикла?

2021-11-06 01:57 UTC, merged