HW07 is completed
leksss/hw-test pull request #8
Opened 2021-08-30 05:23 UTC by leksss

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-09-08 17:46 UTC, kulti requested changes
Алексей, спасибо за вариант решения.

Похоже, что все работает, тесты тоже добавлены. Над чистотой кода еще можно поработать.

Нужны пояснения по промежуточному буферу `buf`. Возможно, я упустил какой-то важный нюанс. Либо он и правда лишний. Возвращаю на доработку до выяснения обстоятельств :)

2021-09-08 17:46 UTC, kulti commented on hw07_file_copying/copy.go
> +		return err
Стоит оборачивать ошибки, чтобы потом было проще разбираться. Например, так return fmt.Errorf("stat: %w", err).

2021-09-08 17:46 UTC, kulti commented on hw07_file_copying/copy.go
> +	iLimit := int(limit)
Не понял, зачем тут и дальше все к int приводить. Для int64 есть метод `Start64`. В любом случае, лучше было бы привести тип один раз в самом конце (а еще перед этим проверить, что он в int влезет, чтобы переполнения избежать).

2021-09-08 17:46 UTC, kulti commented on hw07_file_copying/copy.go
> +	n, err := reader.ReadAt(buf, offset)
Долго думал, зачем нужен буфер и чтение в него. Так и не понял. Кажется, это что-то лишнее.

2021-09-08 17:46 UTC, kulti commented on hw07_file_copying/copy_test.go
> +const OutFile = "out.txt"
Непонятно, зачем эта константа с большой буквы (публичная).

Также не очень хорошо, что все тесты один файл используют. Можно создавать уникальные с помощью https://pkg.go.dev/os#CreateTemp. Тогда тесты можно будет параллельно запускать.

2021-09-08 17:46 UTC, kulti commented on hw07_file_copying/copy_test.go
> +		t.Cleanup(func() { removeOutFile() })
Думаю, `t.Cleanup` стоит писать в начале теста, чтобы он вызвался, если тест выйдет раньше.

2021-09-08 17:46 UTC, kulti commented on hw07_file_copying/copy_test.go
> +			t.Fatal("getting file stat failed")
Зачем смешивать два API для тестирования? Возможно, вы тут хотели прервать тест и упустили, что в testify существует `require`. В данном случае идеально подходит `require.NoError(t, err)`.

PS. Я рекомендую всегда использовать require. Обычно, подробно говорю о причинах на втором занятии на курсе (Тестирование Часть 1)

2021-09-08 17:46 UTC, kulti commented on hw07_file_copying/copy.go
> +		iLimit = int(srcStat.Size() - offset)
Вот так будет чуть лучше читаться (заодно еще убрал int, т.к. они не нужны, но суть не в них):
```
if limit > srcStat.Size() - offset { // если limit больше некоторого значения, то
	limit = srcStat.Size() - offset // присвоить limit это значение
}
```

Как читать текущий вариант, затрудняюсь сказать :)

2021-09-11 04:10 UTC, leksss commented on hw07_file_copying/copy.go
> +		return err
Поправил

2021-09-11 04:11 UTC, leksss commented on hw07_file_copying/copy.go
> +	iLimit := int(limit)
Убрал приведение. Оставил int64

2021-09-11 04:15 UTC, leksss commented on hw07_file_copying/copy.go
> +	n, err := reader.ReadAt(buf, offset)
Буфер нужен для того что бы указать сколько читать.
ReadAt считывает len(buf) байт из файла начиная с offset.

2021-09-11 04:16 UTC, leksss commented on hw07_file_copying/copy_test.go
> +const OutFile = "out.txt"
Константу сделал приватной
Добавил использование CreateTemp

2021-09-11 04:16 UTC, leksss commented on hw07_file_copying/copy_test.go
> +		t.Cleanup(func() { removeOutFile() })
Перенес в начало теста

2021-09-11 04:17 UTC, leksss commented on hw07_file_copying/copy_test.go
> +			t.Fatal("getting file stat failed")
Поправил

2021-09-11 04:17 UTC, leksss commented on hw07_file_copying/copy.go
> +		iLimit = int(srcStat.Size() - offset)
Поправил

2021-09-11 05:26 UTC, kulti commented on hw07_file_copying/copy.go
> +	n, err := reader.ReadAt(buf, offset)
Так буфер же потом никак не используется. Зачем в него что-то читать?

2021-09-11 07:41 UTC, leksss commented on hw07_file_copying/copy.go
> +	n, err := reader.ReadAt(buf, offset)
Reader принимает на вход buf, как параметр для метода Read(), чтобы не нужно было выделять память. Если бы Read() возвращал новый слайс, вместо того, чтобы принимать его как аргумент, ридеру пришлось бы выделять память при каждом вызове Read(). Это была бы катастрофа для сборщика мусора.

https://habr.com/ru/post/306914/

2021-09-11 10:35 UTC, kulti commented on hw07_file_copying/copy.go
> +	n, err := reader.ReadAt(buf, offset)
Алексей, мне кажется, что вы думаете, что это чтение что-то оптимизирует. Цитата объясняет, почему интерфейс именно такой (я люблю этот же пример на занятии про память приводить). Чтение — это просто чтение, копирование байтов в буфер. Мой же вопрос такой — зачем тут читать кусок файла в буфер? Этот буфер никак не используется.

2021-09-12 11:44 UTC, leksss commented on hw07_file_copying/copy.go
> +	n, err := reader.ReadAt(buf, offset)
Я не совсем понял вопрос. Удалил переменную buf. Возможно вы это имели ввиду?

2021-09-19 06:12 UTC, kulti commented on hw07_file_copying/copy.go
> +	n, err := reader.ReadAt(buf, offset)
Алексей, пожалуйста, объясните, зачем нужен вызов `ReadAt`? Что полезного он делает?

Я не понимаю, что вы хотели сделать в этом месте. Вижу, что у вас какое-то непонимание, но не понимаю, в чем оно. Поэтому не могу вам объяснить и помочь.

2021-09-19 06:12 UTC, kulti commented on hw07_file_copying/copy.go
> +	n, err := reader.ReadAt(buf, offset)
Будет лучше, если напишите мне в слаке. Там мы быстрее поймем друг друга.

2021-10-03 11:10 UTC, kulti approved these changes
Алексей, здорово, что наконец-то разобрались с непонятным мне моментом. Надеюсь, ваше понимание, как работать с ридерами, тоже улучшилось.

ДЗ принято — 10/10.

2021-10-05 06:56 UTC, merged